### ISSUE TITLE
Status URL implementation

### ISSUE THREAD

**Issue by eneski** [okkype/wemos_relay#1]
Hello, this sketch was very helpful for me, because I want to use my WeMos with relay shield in connection with Homebridge. The only thing I need to finish my project is to have an status url which tells Homebridge which current status the relay has. I really don't know how to do this, as I don't really have that much experience with coding. https://github.com/rudders/homebridge-http This is the page of the project. I need a link like 192.168.178.1.1/status which posts an integer of 1 or 0. At least that's what it says on the page. It would be really really nice of you if you could implement this or maybe tell me how it works if you know it. I have been asking around for a long time but no one seems to be able to help me or they just don't want to :D

**Comment by okkype** [comment]
you can access http://[ip of wemos]/ to see relay status on json or http://[ip of wemos]/ui to see relay status human readable
